title: Joey' Home
description: 4 what
author: Joey Chen
# github: https://gitlab.com/ComplicatedPhenomenon
about: Time never lies
# google_analytics:
avatar_url: /static/img/av84n.jpg

enableTags: true
tagarray: []


social:
    - icon: fa-twitter
      link: 
    - icon: fa-stack-exchange
      link: 
    - icon: fa-gitlab
      link: 

share:
  twitter_username: 

urls:
    - text: About
      url: /about/
    - text: XML Feed
      url: /feed.xml

url: "https:/joeyhome/"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
kramdown:
  parse_block_html: true
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-feed
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
